---
- hosts: staging
  become: true
  gather_facts: false
  tasks:
    - name: Set kernel parameters
      sysctl:
        name: vm.swappiness
        value: 0
        state: present
        sysctl_set: yes
    - name: INSTALL Ceph Repository Info
      yum: name="centos-release-ceph-luminous" state=installed
    - name: INSTALL Common Software
      yum: name={{item}} state=installed
      with_items:
        - ceph
