---
- hosts: staging
  become: true
  gather_facts: false
  tasks:
    - name: Set kernel parameters
      sysctl:
        name: vm.swappiness
        value: 0
        state: present
        sysctl_set: yes
    - name: INSTALL Ceph Repository Info
      yum: name="centos-release-ceph-luminous" state=installed
    - name: INSTALL Common Software
      yum: name={{item}} state=installed
      with_items:
        - ceph
    - name: Remove swap from fstab
      lineinfile:
        dest: /etc/fstab
        regexp: 'swap'
        state: absent
    - name: Make sure firewall service is not installed
      yum: name=firewalld state=absent
    - name: Enforce SELinux off
      selinux:
        policy: targeted
        state: permissive

    # Write sudoers file
    - name: Write sudoers file
      lineinfile:
        dest: /etc/sudoers.d/devin
        line: "devin ALL = (ALL) NOPASSWD:ALL"
        create: yes


# need to create user accounts that the sudoers file allows