---
- hosts: cluster
  become: true
  gather_facts: false
  handlers:
    - name: swapoff
      command: swapoff -a
  tasks:
    - name: Set kernel parameters
      sysctl:
        name: vm.swappiness
        value: 0
        state: present
        sysctl_set: yes
    - name: INSTALL Ceph Repository Info
      yum: name="centos-release-ceph-luminous" state=installed
    - name: INSTALL Common Software
      yum: name={{item}} state=installed
      with_items:
        - ceph
    - name: Remove swap from fstab
      lineinfile:
        dest: /etc/fstab
        regexp: 'swap'
        state: absent
      notify: swapoff
    - name: Make sure firewall service is not installed
      yum: name=firewalld state=absent
    - name: Enforce SELinux off
      selinux:
        policy: targeted
        state: permissive

    # Write sudoers file
    - name: Write sudoers file
      lineinfile:
        dest: /etc/sudoers.d/devin
        line: "devin ALL = (ALL) NOPASSWD:ALL"
        create: yes

    - name: Setup Kernel Repo
      yum: name="http://www.elrepo.org/elrepo-release-7.0-3.el7.elrepo.noarch.rpm" state=present
    - name: Update to current kernel
      yum: name="kernel-ml" state=present enablerepo=elrepo-kernel
    - name: Update to current kernel tools
      yum: name="kernel-ml-tools" state=present enablerepo=elrepo-kernel

# need to create user accounts that the sudoers file allows

